#!/usr/local/bin/Rscript
# script to calculate RPKM from counts.txt table 
# (C) Yuri Kravatsky, lokapal@gmail.com, jiri@eimb.ru
# Input:  counts.txt generated by featureCounts
# Output: 1. counts.byRPKM.txt     
#         2. counts.byCounts.txt   
#
# Dependency tools & libraries:
# 1. R
# Common R libraries:
# 2. dplyr

suppressPackageStartupMessages(library(dplyr))

#counts a numeric matrix of raw feature counts.
#featureLength a numeric vector with feature lengths that can be obtained using biomaRt package.
#meanFragmentLength a numeric vector with mean fragment lengths, which can be calculated using the CollectInsertSizeMetrics(Picard) tool.

counts <- as.data.frame(read.table("counts.txt", header=TRUE, sep='\t', skip = 1, row.names=NULL, stringsAsFactors = FALSE))

namescounts <- vector()
namesRPKMs  <- vector()

for (i in 7:ncol(counts))  {
    countname <- colnames(counts[i])
    namescounts <- append (namescounts, countname)
    totalReads <- sum(counts[[countname]])
    RPKname <- gsub("(\\.[A-Za-z0-9]+)$", ".RPKM", countname)
    namesRPKMs <- append (namesRPKMs, RPKname)
    counts  <- counts %>% mutate (!!sym(RPKname) := !!sym(countname) / (Length/1000.0 * totalReads/1e6)) %>% mutate (!!sym(RPKname) := sprintf("%.4f", !!sym(RPKname)))
    counts[[RPKname]] <- as.numeric(as.character(counts[[RPKname]]))
                           }

counts <- counts  %>%  mutate(MeanCounts = rowMeans(select(., all_of(namescounts)))) %>%
                       mutate(MeanRPKMs  = rowMeans(select(., all_of(namesRPKMs)))) %>%
# The select to skip unknown number of first columns except of
                       select (-c(all_of(namescounts), MeanCounts, all_of(namesRPKMs), MeanRPKMs), all_of(namescounts), MeanCounts, all_of(namesRPKMs), MeanRPKMs) %>%
#                       select (1:6, all_of(namescounts), MeanCounts, all_of(namesRPKMs), MeanRPKMs) %>%
                       arrange(desc(MeanRPKMs)) %>%
                       filter(MeanCounts != 0)

outfile <- paste0("counts.byRPKM.txt")
write.table(counts, file=outfile, row.names=F, col.names=T, sep="\t", quote=F)

counts <- counts  %>%  arrange(desc(MeanCounts))
outfile <- paste0("counts.byCounts.txt")
write.table(counts, file=outfile, row.names=F, col.names=T, sep="\t", quote=F)
